CREATE TABLE IF NOT EXISTS inv_invoice
(
    inv_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_number           VARCHAR(255) NOT NULL,
    inv_access_key       VARCHAR(255) NOT NULL UNIQUE,
    inv_issue_date       TIMESTAMP    NOT NULL,
    inv_issuer_tax_id    VARCHAR(255) NOT NULL,
    inv_issuer_name      VARCHAR(255) NOT NULL,
    inv_recipient_tax_id VARCHAR(255) NOT NULL,
    inv_recipient_name   VARCHAR(255) NOT NULL,
    inv_total_amount     DECIMAL(19, 2),
    inv_status           VARCHAR(255) NOT NULL,
    inv_notes            VARCHAR(255),
    CONSTRAINT unique_access_key UNIQUE (inv_access_key)
    );

CREATE TABLE IF NOT EXISTS ini_invoice_item
(
    ini_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ini_invoice_id   BIGINT         NOT NULL,
    ini_name         VARCHAR(255)   NOT NULL,
    ini_measure_unit VARCHAR(255)   NOT NULL,
    ini_quantity     INT            NOT NULL,
    ini_unit_price   DECIMAL(19, 2) NOT NULL,
    CONSTRAINT fk_invoice FOREIGN KEY (ini_invoice_id) REFERENCES inv_invoice (inv_id)
    );
