spring:
  profiles:
    active: test
  application:
    name: InvoiceAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres_user_product
    password: super_password
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: true

client:
  logistock:
    url: http://localhost:8080