spring:
  application:
    name: InvoiceAPI
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    open-in-view: true

client:
  logistock:
    url: logistock-url